const express=require('express');
const storeRouter=express.Router();
const storeController = require('../controllers/storeController');
storeRouter.get("/",storeController.getIndex);
storeRouter.get("/homes",storeController.getHome);
storeRouter.get("/bookings",storeController.getBookings);
storeRouter.get("/favourites",storeController.getFavouriteList);
storeRouter.get("/homes/:id",storeController.getHomeDetails);
storeRouter.post("/favourites",storeController.postAddToFavourites);
storeRouter.post("/favourites/delete/:id",storeController.postDeleteFromFavourites);
module.exports=storeRouter;
